/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/behavior_actions.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "engine/graph_node.h"
#include "game/behavior_actions.h"
#include "game/level_update.h"
#include "game/object_helpers.h"
#include "game/object_list_processor.h"
#include "game/rendering_graph_node.h"

/* src/game/behavior_actions.c: geo_move_mario_part_from_parent */
Gfx *geo_move_mario_part_from_parent(s32 run, UNUSED struct GraphNode *node, Mat4 mtx) {
    if (run == TRUE) {
        Mat4 sp20;
        struct Object *obj = (struct Object *) gCurGraphNodeObject;
        if (obj == gMarioObject && obj->prevObj != NULL) {
            create_transformation_from_matrices(sp20, mtx, *gCurGraphNodeCamera->matrixPtr);
            obj_update_pos_from_parent_transformation(sp20, obj->prevObj);
            obj_set_gfx_pos_from_pos(obj->prevObj);
        }
    }

    return NULL;
}
