/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/behaviors/coin.inc.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "behavior_data.h"
#include "model_ids.h"
#include "engine/behavior_script.h"
#include "engine/math_util.h"
#include "engine/surface_collision.h"
#include "game/interaction.h"
#include "game/object_helpers.h"
#include "game/object_list_processor.h"
#include "coin_boundary.h"

/* src/game/behaviors/coin.inc.c: struct ObjectHitbox sYellowCoinHitbox */
struct ObjectHitbox sYellowCoinHitbox = {
    /* interactType:      */ INTERACT_COIN,
    /* downOffset:        */ 0,
    /* damageOrCoinValue: */ 1,
    /* health:            */ 0,
    /* numLootCoins:      */ 0,
    /* radius:            */ 100,
    /* height:            */ 64,
    /* hurtboxRadius:     */ 0,
    /* hurtboxHeight:     */ 0,
};

/* src/game/behaviors/coin.inc.c: bhv_coin_sparkles_init */
s32 bhv_coin_sparkles_init(void) {
    if (o->oInteractStatus & INT_STATUS_INTERACTED
        && !(o->oInteractStatus & INT_STATUS_TOUCHED_BOB_OMB)) {
        spawn_object(o, MODEL_SPARKLES, bhvGoldenCoinSparkles);
        obj_mark_for_deletion(o);
        return TRUE;
    }

    o->oInteractStatus = 0;

    return FALSE;
}

/* src/game/behaviors/coin.inc.c: bhv_yellow_coin_init */
void bhv_yellow_coin_init(void) {
    cur_obj_set_behavior(bhvYellowCoin);
    obj_set_hitbox(o, &sYellowCoinHitbox);
    bhv_init_room();
    cur_obj_update_floor_height();

    if (500.0f < absf(o->oPosY - o->oFloorHeight)) {
        cur_obj_set_model(MODEL_YELLOW_COIN_NO_SHADOW);
    }

    if (o->oFloorHeight < FLOOR_LOWER_LIMIT_MISC) {
        obj_mark_for_deletion(o);
    }
}

/* src/game/behaviors/coin.inc.c: bhv_yellow_coin_loop */
void bhv_yellow_coin_loop(void) {
    bhv_coin_sparkles_init();
    o->oAnimState++;
}

/* src/game/behaviors/coin.inc.c: bhv_coin_formation_spawn_loop */
void bhv_coin_formation_spawn_loop(void) {
    if (o->oTimer == 0) {
        cur_obj_set_behavior(bhvYellowCoin);
        obj_set_hitbox(o, &sYellowCoinHitbox);
        bhv_init_room();

        if (o->oCoinOnGround) {
            o->oPosY += 300.0f;
            cur_obj_update_floor_height();

            if (o->oPosY < o->oFloorHeight || o->oFloorHeight < FLOOR_LOWER_LIMIT_MISC) {
                obj_mark_for_deletion(o);
            } else {
                o->oPosY = o->oFloorHeight;
            }
        } else {
            cur_obj_update_floor_height();

            if (absf(o->oPosY - o->oFloorHeight) > 250.0f) {
                cur_obj_set_model(MODEL_YELLOW_COIN_NO_SHADOW);
            }
        }
    } else {
        if (bhv_coin_sparkles_init()) {
            o->parentObj->oCoinCollectedFlags |= bit_shift_left(o->oBhvParams2ndByte);
        }
        o->oAnimState++;
    }

    if (o->parentObj->oAction == COIN_FORMATION_ACT_RESPAWN_COINS) {
        obj_mark_for_deletion(o);
    }
}

/* src/game/behaviors/coin.inc.c: s16 sCoinArrowPositions[][2] */
s16 sCoinArrowPositions[][2] = {
    { 0, -150 },
    { 0, -50 },
    { 0, 50 },
    { 0, 150 },
    { -50, 100 },
    { -100, 50 },
    { 50, 100 },
    { 100, 50 },
};

/* src/game/behaviors/coin.inc.c: spawn_coin_in_formation */
void spawn_coin_in_formation(s32 coinIndex, s32 coinFormationFlags) {
    struct Object *coinSpawner;
    Vec3i pos;
    s32 setSpawner = TRUE;
    s32 onGround = TRUE;

    pos[0] = pos[1] = pos[2] = 0;

    switch (coinFormationFlags & COIN_FORMATION_BP_FLAG_MASK) {
        case COIN_FORMATION_BP_LINE_HORIZONTAL:
            pos[2] = 160 * (coinIndex - 2);
            if (coinIndex > 4) {
                setSpawner = FALSE;
            }
            break;

        case COIN_FORMATION_BP_LINE_VERTICAL:
            onGround = FALSE;
            pos[1] = 160 * coinIndex * 0.8; // 128 * coinIndex
            if (coinIndex > 4) {
                setSpawner = FALSE;
            }
            break;

        case COIN_FORMATION_BP_RING_HORIZONTAL:
            pos[0] = sins(coinIndex << 13) * 300.0f;
            pos[2] = coss(coinIndex << 13) * 300.0f;
            break;

        case COIN_FORMATION_BP_RING_VERTICAL:
            onGround = FALSE;
            pos[0] = coss(coinIndex << 13) * 200.0f;
            pos[1] = sins(coinIndex << 13) * 200.0f + 200.0f;
            break;

        case COIN_FORMATION_BP_ARROW:
            pos[0] = sCoinArrowPositions[coinIndex][0];
            pos[2] = sCoinArrowPositions[coinIndex][1];
            break;
    }

    if (coinFormationFlags & COIN_FORMATION_BP_FLAG_FLYING) {
        onGround = FALSE;
    }

    if (setSpawner) {
        coinSpawner = spawn_object_relative(coinIndex, pos[0], pos[1], pos[2], o,
                                            MODEL_YELLOW_COIN, bhvCoinFormationSpawn);
        coinSpawner->oCoinOnGround = onGround;
    }
}

/* src/game/behaviors/coin.inc.c: bhv_coin_formation_init */
void bhv_coin_formation_init(void) {
    o->oCoinCollectedFlags = (o->oBhvParams >> 8) & 0xFF;
}

/* src/game/behaviors/coin.inc.c: bhv_coin_formation_loop */
void bhv_coin_formation_loop(void) {
    s32 coinIndex;

    switch (o->oAction) {
        case COIN_FORMATION_ACT_SPAWN_COINS:
            if (o->oDistanceToMario < 2000.0f) {
                for (coinIndex = 0; coinIndex <= 7; coinIndex++) {
                    if (!(o->oCoinCollectedFlags & (1 << coinIndex))) {
                        spawn_coin_in_formation(coinIndex, o->oBhvParams2ndByte);
                    }
                }
                o->oAction++;
            }
            break;

        case COIN_FORMATION_ACT_IDLE:
            if (o->oDistanceToMario > 2100.0f) {
                o->oAction++;
            }
            break;

        case COIN_FORMATION_ACT_RESPAWN_COINS:
            o->oAction = COIN_FORMATION_ACT_SPAWN_COINS;
            break;
    }

    set_object_respawn_info_bits(o, o->oCoinCollectedFlags & 0xFF);
}

/* src/game/behaviors/coin.inc.c: bhv_coin_sparkles_loop */
void bhv_coin_sparkles_loop(void) {
    cur_obj_scale(0.6f);
}

/* src/game/behaviors/coin.inc.c: bhv_golden_coin_sparkles_loop */
void bhv_golden_coin_sparkles_loop(void) {
    struct Object *sparkles;
    UNUSED u8 filler[4];
    f32 sp24 = 30.0f;

    sparkles = spawn_object(o, MODEL_SPARKLES, bhvCoinSparkles);
    sparkles->oPosX += random_float() * sp24 - sp24 / 2;
    sparkles->oPosZ += random_float() * sp24 - sp24 / 2;
}
