/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/behaviors/explosion.inc.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */

/* src/game/behaviors/explosion.inc.c: bhv_explosion_init */
void bhv_explosion_init(void) {
    create_sound_spawner(SOUND_GENERAL2_BOBOMB_EXPLOSION);
    set_environmental_camera_shake(SHAKE_ENV_EXPLOSION);

    o->oOpacity = 255;
}

/* src/game/behaviors/explosion.inc.c: bhv_explosion_loop */
void bhv_explosion_loop(void) {
    s32 i;

    if (o->oTimer == 9) {
        if (find_water_level(o->oPosX, o->oPosZ) > o->oPosY) {
            for (i = 0; i < 40; i++) {
                spawn_object(o, MODEL_WHITE_PARTICLE_SMALL, bhvBobombExplosionBubble);
            }
        } else {
            spawn_object(o, MODEL_SMOKE, bhvBobombBullyDeathSmoke);
        }

        o->activeFlags = ACTIVE_FLAG_DEACTIVATED;
    }

    o->oOpacity -= 14;

    cur_obj_scale((f32) o->oTimer / 9.0f + 1.0);
}
