/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/engine/geo_layout.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "engine/graph_node.h"

/* src/engine/geo_layout.c: struct GraphNode gObjParentGraphNode */
struct GraphNode gObjParentGraphNode;
