/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/geo_misc.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from pinned source; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "shadow_boundary.h"

/* src/game/geo_misc.c: round_float */
s16 round_float(f32 num) {
    // Note that double literals are used here, rather than float literals.
    if (num >= 0.0) {
        return num + 0.5;
    } else {
        return num - 0.5;
    }
}

/* src/game/geo_misc.c: #ifndef GBI_FLOATS */
#ifndef GBI_FLOATS
void make_vertex(Vtx *vtx, s32 n, s16 x, s16 y, s16 z, s16 tx, s16 ty, u8 r, u8 g, u8 b, u8 a)
#else
void make_vertex(Vtx *vtx, s32 n, f32 x, f32 y, f32 z, s16 tx, s16 ty, u8 r, u8 g, u8 b, u8 a)
#endif
{
    vtx[n].v.ob[0] = x;
    vtx[n].v.ob[1] = y;
    vtx[n].v.ob[2] = z;

    vtx[n].v.flag = 0;

    vtx[n].v.tc[0] = tx;
    vtx[n].v.tc[1] = ty;

    vtx[n].v.cn[0] = r;
    vtx[n].v.cn[1] = g;
    vtx[n].v.cn[2] = b;
    vtx[n].v.cn[3] = a;
}
