/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * include/macro_presets.inc.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"

/* include/macro_presets.inc.c: struct MacroPreset */
struct MacroPreset {
    /* 0x00 */ const BehaviorScript *behavior;
    /* 0x04 */ s16 model;
    /* 0x06 */ s16 param;
};
