/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/macro_special_objects.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "model_ids.h"
#include "behavior_data.h"
#include "engine/surface_load.h"
#include "game/macro_special_objects.h"
#include "game/object_helpers.h"
#include "game/object_list_processor.h"
#include "special_presets.inc.c"
#include "excerpts/macro_preset_struct.inc.c"
#include "macro_preset_boundary.h"

/* src/game/macro_special_objects.c: convert_rotation */
s16 convert_rotation(s16 inRotation) {
    u16 rotation = ((u16)(inRotation & 0xFF));
    rotation <<= 8;

    if (rotation == 0x3F00) {
        rotation = 0x4000;
    }

    if (rotation == 0x7F00) {
        rotation = 0x8000;
    }

    if (rotation == 0xBF00) {
        rotation = 0xC000;
    }

    if (rotation == 0xFF00) {
        rotation = 0x0000;
    }

    return (s16) rotation;
}

/* src/game/macro_special_objects.c: #define MACRO_OBJ_Y_ROT 0 */
#define MACRO_OBJ_Y_ROT 0

/* src/game/macro_special_objects.c: #define MACRO_OBJ_X 1 */
#define MACRO_OBJ_X 1

/* src/game/macro_special_objects.c: #define MACRO_OBJ_Y 2 */
#define MACRO_OBJ_Y 2

/* src/game/macro_special_objects.c: #define MACRO_OBJ_Z 3 */
#define MACRO_OBJ_Z 3

/* src/game/macro_special_objects.c: #define MACRO_OBJ_PARAMS 4 */
#define MACRO_OBJ_PARAMS 4

/* src/game/macro_special_objects.c: struct LoadedPreset */
struct LoadedPreset {
    /* 0x00 */ const BehaviorScript *behavior;
    /* 0x04 */ s16 param; // huh? why does the below function swap these.. just use the struct..
    /* 0x06 */ s16 model;
};

/* src/game/macro_special_objects.c: spawn_macro_objects */
void spawn_macro_objects(s16 areaIndex, s16 *macroObjList) {
    UNUSED u8 filler[4];
    s32 presetID;

    s16 macroObject[5]; // see the 5 #define statements above
    struct Object *newObj;
    struct LoadedPreset preset;

    gMacroObjectDefaultParent.header.gfx.areaIndex = areaIndex;
    gMacroObjectDefaultParent.header.gfx.activeAreaIndex = areaIndex;

    while (TRUE) {
        if (*macroObjList == -1) { // An encountered value of -1 means the list has ended.
            break;
        }

        presetID = (*macroObjList & 0x1FF) - 31; // Preset identifier for sMacroObjectPresets array

        if (presetID < 0) {
            break;
        }

        // Set macro object properties from the list
        macroObject[MACRO_OBJ_Y_ROT] = ((*macroObjList++ >> 9) & 0x7F) << 1; // Y-Rotation
        macroObject[MACRO_OBJ_X] = *macroObjList++;                          // X position
        macroObject[MACRO_OBJ_Y] = *macroObjList++;                          // Y position
        macroObject[MACRO_OBJ_Z] = *macroObjList++;                          // Z position
        macroObject[MACRO_OBJ_PARAMS] = *macroObjList++;                     // Behavior params

        // Get the preset values from the sMacroObjectPresets list.
        preset.model = sMacroObjectPresets[presetID].model;
        preset.behavior = sMacroObjectPresets[presetID].behavior;
        preset.param = sMacroObjectPresets[presetID].param;

        if (preset.param != 0) {
            macroObject[MACRO_OBJ_PARAMS] =
                (macroObject[MACRO_OBJ_PARAMS] & 0xFF00) + (preset.param & 0x00FF);
        }

        // If object has been killed, prevent it from respawning
        if (((macroObject[MACRO_OBJ_PARAMS] >> 8) & RESPAWN_INFO_DONT_RESPAWN)
            != RESPAWN_INFO_DONT_RESPAWN) {
            // Spawn the new macro object.
            newObj = spawn_object_abs_with_rot(
                         &gMacroObjectDefaultParent, // Parent object
                         0,                          // Unused
                         preset.model,               // Model ID
                         preset.behavior,            // Behavior address
                         macroObject[MACRO_OBJ_X],   // X-position
                         macroObject[MACRO_OBJ_Y],   // Y-position
                         macroObject[MACRO_OBJ_Z],   // Z-position
                         0,                          // X-rotation
                         convert_rotation(macroObject[MACRO_OBJ_Y_ROT]), // Y-rotation
                         0                                               // Z-rotation
                     );

            newObj->oUnusedBhvParams = macroObject[MACRO_OBJ_PARAMS];
            newObj->oBhvParams = ((macroObject[MACRO_OBJ_PARAMS] & 0x00FF) << 16)
                                 + (macroObject[MACRO_OBJ_PARAMS] & 0xFF00);
            newObj->oBhvParams2ndByte = macroObject[MACRO_OBJ_PARAMS] & 0x00FF;
            newObj->respawnInfoType = RESPAWN_INFO_TYPE_16;
            newObj->respawnInfo = macroObjList - 1;
            newObj->parentObj = newObj;
        }
    }
}

/* src/game/macro_special_objects.c: spawn_special_objects */
void spawn_special_objects(s16 areaIndex, TerrainData **specialObjList) {
    s32 numOfSpecialObjects;
    s32 i;
    s32 offset;
    s16 x;
    s16 y;
    s16 z;
    s16 extraParams[4];
    u8 model;
    u8 type;
    u8 presetID;
    u8 defaultParam;
    const BehaviorScript *behavior;

    numOfSpecialObjects = **specialObjList;
    (*specialObjList)++;

    gMacroObjectDefaultParent.header.gfx.areaIndex = areaIndex;
    gMacroObjectDefaultParent.header.gfx.activeAreaIndex = areaIndex;

    for (i = 0; i < numOfSpecialObjects; i++) {
        presetID = (u8) **specialObjList;
        (*specialObjList)++;
        x = **specialObjList;
        (*specialObjList)++;
        y = **specialObjList;
        (*specialObjList)++;
        z = **specialObjList;
        (*specialObjList)++;

        offset = 0;
        while (TRUE) {
            if (sSpecialObjectPresets[offset].presetID == presetID) {
                break;
            }

            if (sSpecialObjectPresets[offset].presetID == special_null_end) {
            }

            offset++;
        }

        model = sSpecialObjectPresets[offset].model;
        behavior = sSpecialObjectPresets[offset].behavior;
        type = sSpecialObjectPresets[offset].type;
        defaultParam = sSpecialObjectPresets[offset].defParam;

        switch (type) {
            case SPTYPE_NO_YROT_OR_PARAMS:
                spawn_macro_abs_yrot_2params(model, behavior, x, y, z, 0, 0);
                break;
            case SPTYPE_YROT_NO_PARAMS:
                extraParams[0] = **specialObjList; // Y-rotation
                (*specialObjList)++;
                spawn_macro_abs_yrot_2params(model, behavior, x, y, z, extraParams[0], 0);
                break;
            case SPTYPE_PARAMS_AND_YROT:
                extraParams[0] = **specialObjList; // Y-rotation
                (*specialObjList)++;
                extraParams[1] = **specialObjList; // Params
                (*specialObjList)++;
                spawn_macro_abs_yrot_2params(model, behavior, x, y, z, extraParams[0], extraParams[1]);
                break;
            case SPTYPE_UNKNOWN:
                extraParams[0] =
                    **specialObjList; // Unknown, gets put into obj->oMacroUnk108 as a float
                (*specialObjList)++;
                extraParams[1] =
                    **specialObjList; // Unknown, gets put into obj->oMacroUnk10C as a float
                (*specialObjList)++;
                extraParams[2] =
                    **specialObjList; // Unknown, gets put into obj->oMacroUnk110 as a float
                (*specialObjList)++;
                spawn_macro_abs_special(model, behavior, x, y, z, extraParams[0], extraParams[1],
                                        extraParams[2]);
                break;
            case SPTYPE_DEF_PARAM_AND_YROT:
                extraParams[0] = **specialObjList; // Y-rotation
                (*specialObjList)++;
                spawn_macro_abs_yrot_param1(model, behavior, x, y, z, extraParams[0], defaultParam);
                break;
            default:
                break;
        }
    }
}

/* src/game/macro_special_objects.c: get_special_objects_size */
u32 get_special_objects_size(s16 *data) {
    s16 *startPos = data;
    s32 numOfSpecialObjects;
    s32 i;
    u8 presetID;
    s32 offset;

    numOfSpecialObjects = *data++;

    for (i = 0; i < numOfSpecialObjects; i++) {
        presetID = (u8) *data++;
        data += 3;
        offset = 0;

        while (TRUE) {
            if (sSpecialObjectPresets[offset].presetID == presetID) {
                break;
            }
            offset++;
        }

        switch (sSpecialObjectPresets[offset].type) {
            case SPTYPE_NO_YROT_OR_PARAMS:
                break;
            case SPTYPE_YROT_NO_PARAMS:
                data++;
                break;
            case SPTYPE_PARAMS_AND_YROT:
                data += 2;
                break;
            case SPTYPE_UNKNOWN:
                data += 3;
                break;
            case SPTYPE_DEF_PARAM_AND_YROT:
                data++;
                break;
            default:
                break;
        }
    }

    return data - startPos;
}
