/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/object_helpers.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "game/object_helpers.h"

/* src/game/object_helpers.c: absf */
f32 absf(f32 x) {
    if (x >= 0) {
        return x;
    } else {
        return -x;
    }
}
