/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/rendering_graph_node.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "engine/graph_node.h"
#include "game/memory.h"
#include "game/rendering_graph_node.h"

/* src/game/rendering_graph_node.c: u8 gCurrAnimType */
u8 gCurrAnimType;

/* src/game/rendering_graph_node.c: u8 gCurrAnimEnabled */
u8 gCurrAnimEnabled;

/* src/game/rendering_graph_node.c: s16 gCurrAnimFrame */
s16 gCurrAnimFrame;

/* src/game/rendering_graph_node.c: f32 gCurrAnimTranslationMultiplier */
f32 gCurrAnimTranslationMultiplier;

/* src/game/rendering_graph_node.c: u16 *gCurrAnimAttribute */
u16 *gCurrAnimAttribute;

/* src/game/rendering_graph_node.c: s16 *gCurrAnimData */
s16 *gCurrAnimData;

/* src/game/rendering_graph_node.c: geo_set_animation_globals */
void geo_set_animation_globals(struct AnimInfo *node, s32 hasAnimation) {
    struct Animation *anim = node->curAnim;

    if (hasAnimation) {
        node->animFrame = geo_update_animation_frame(node, &node->animFrameAccelAssist);
    }
    node->animTimer = gAreaUpdateCounter;
    if (anim->flags & ANIM_FLAG_HOR_TRANS) {
        gCurrAnimType = ANIM_TYPE_VERTICAL_TRANSLATION;
    } else if (anim->flags & ANIM_FLAG_VERT_TRANS) {
        gCurrAnimType = ANIM_TYPE_LATERAL_TRANSLATION;
    } else if (anim->flags & ANIM_FLAG_6) {
        gCurrAnimType = ANIM_TYPE_NO_TRANSLATION;
    } else {
        gCurrAnimType = ANIM_TYPE_TRANSLATION;
    }

    gCurrAnimFrame = node->animFrame;
    gCurrAnimEnabled = (anim->flags & ANIM_FLAG_5) == 0;
    gCurrAnimAttribute = segmented_to_virtual((void *) anim->index);
    gCurrAnimData = segmented_to_virtual((void *) anim->values);

    if (anim->animYTransDivisor == 0) {
        gCurrAnimTranslationMultiplier = 1.0f;
    } else {
        gCurrAnimTranslationMultiplier = (f32) node->animYTrans / (f32) anim->animYTransDivisor;
    }
}
