/* Verbatim CC0 excerpts from n64decomp/sm64 9921382a68bb0c865e5e45eb594d9c64db59b1af
 * src/game/behaviors/sound_spawner.inc.c, between the item markers. Generated by
 * oracle/tools/extract_excerpts.py from a clean pinned checkout; do not
 * edit. The include lines are authored (MIT). Item SHA-1s: oracle/README.md. */
#include "sm64.h"
#include "audio/external.h"
#include "game/object_list_processor.h"
#include "coin_boundary.h"

/* src/game/behaviors/sound_spawner.inc.c: bhv_sound_spawner_init */
void bhv_sound_spawner_init(void) {
    s32 sp1C = o->oSoundEffectUnkF4;
    play_sound(sp1C, o->header.gfx.cameraToObject);
}
