//! Original constants used by the ported Mario code, generated from the pinned
//! CC0 decomp headers (include/sm64.h, include/surface_terrains.h,
//! include/sounds.h, include/level_table.h) as evaluated by the C compiler.
//! `rustario64-oracle` tests that every value still matches those headers.

pub const ACT_TWIRLING: u32 = 0x1080_08A4;
pub const ACT_SHOT_FROM_CANNON: u32 = 0x0088_0898;
pub const ACT_LONG_JUMP: u32 = 0x0300_0888;
pub const ACT_SLIDE_KICK: u32 = 0x0180_08AA;
pub const ACT_BBH_ENTER_SPIN: u32 = 0x0000_1535;
pub const ACT_LAVA_BOOST: u32 = 0x0102_08B7;
pub const ACT_FALL_AFTER_STAR_GRAB: u32 = 0x0000_1904;
pub const ACT_GETTING_BLOWN: u32 = 0x0102_08B8;
pub const ACT_GROUND_POUND: u32 = 0x0080_08A9;
pub const ACT_FLYING: u32 = 0x1088_0899;
pub const ACT_CRAWLING: u32 = 0x0400_8448;
pub const ACT_QUICKSAND_DEATH: u32 = 0x0002_1312;
pub const ACT_IDLE: u32 = 0x0C40_0201;
pub const ACT_WALKING: u32 = 0x0400_0440;
pub const ACT_FREEFALL: u32 = 0x0100_088C;
pub const ACT_JUMP: u32 = 0x0300_0880;
pub const ACT_FLAG_STATIONARY: u32 = 0x0000_0200;
pub const ACT_FLAG_MOVING: u32 = 0x0000_0400;
pub const ACT_FLAG_AIR: u32 = 0x0000_0800;
pub const ACT_FLAG_INTANGIBLE: u32 = 0x0000_1000;
pub const ACT_FLAG_INVULNERABLE: u32 = 0x0002_0000;
pub const ACT_FLAG_RIDING_SHELL: u32 = 0x0001_0000;
pub const ACT_FLAG_CONTROL_JUMP_HEIGHT: u32 = 0x0200_0000;
pub const ACT_FLAG_METAL_WATER: u32 = 0x0000_4000;
pub const MARIO_VANISH_CAP: u32 = 2;
pub const MARIO_METAL_CAP: u32 = 4;
pub const MARIO_WING_CAP: u32 = 8;
pub const MARIO_UNKNOWN_08: u32 = 0x0000_0100;
pub const MARIO_UNKNOWN_30: u32 = 0x4000_0000;
pub const INPUT_A_DOWN: u16 = 0x0080;
pub const GROUND_STEP_LEFT_GROUND: u32 = 0;
pub const GROUND_STEP_NONE: u32 = 1;
pub const GROUND_STEP_HIT_WALL: u32 = 2;
pub const GROUND_STEP_HIT_WALL_STOP_QSTEPS: u32 = 2;
pub const GROUND_STEP_HIT_WALL_CONTINUE_QSTEPS: u32 = 3;
pub const AIR_STEP_CHECK_LEDGE_GRAB: u32 = 1;
pub const AIR_STEP_CHECK_HANG: u32 = 2;
pub const AIR_STEP_NONE: u32 = 0;
pub const AIR_STEP_LANDED: u32 = 1;
pub const AIR_STEP_HIT_WALL: u32 = 2;
pub const AIR_STEP_GRABBED_LEDGE: u32 = 3;
pub const AIR_STEP_GRABBED_CEILING: u32 = 4;
pub const AIR_STEP_HIT_LAVA_WALL: u32 = 6;
pub const SURFACE_DEFAULT: i16 = 0;
pub const SURFACE_BURNING: i16 = 1;
pub const SURFACE_HANGABLE: i16 = 5;
pub const SURFACE_SLOW: i16 = 9;
pub const SURFACE_VERY_SLIPPERY: i16 = 19;
pub const SURFACE_SLIPPERY: i16 = 20;
pub const SURFACE_NOT_SLIPPERY: i16 = 21;
pub const SURFACE_SHALLOW_QUICKSAND: i16 = 33;
pub const SURFACE_DEEP_QUICKSAND: i16 = 34;
pub const SURFACE_INSTANT_QUICKSAND: i16 = 35;
pub const SURFACE_DEEP_MOVING_QUICKSAND: i16 = 36;
pub const SURFACE_SHALLOW_MOVING_QUICKSAND: i16 = 37;
pub const SURFACE_QUICKSAND: i16 = 38;
pub const SURFACE_MOVING_QUICKSAND: i16 = 39;
pub const SURFACE_INSTANT_MOVING_QUICKSAND: i16 = 45;
pub const SURFACE_HORIZONTAL_WIND: i16 = 44;
pub const SURFACE_VERTICAL_WIND: i16 = 56;
pub const SURFACE_HARD: i16 = 48;
pub const SURFACE_HARD_SLIPPERY: i16 = 53;
pub const SURFACE_HARD_VERY_SLIPPERY: i16 = 54;
pub const SURFACE_HARD_NOT_SLIPPERY: i16 = 55;
pub const SURFACE_ICE: i16 = 46;
pub const SURFACE_NOISE_DEFAULT: i16 = 41;
pub const SURFACE_NOISE_SLIPPERY: i16 = 42;
pub const SURFACE_NOISE_VERY_SLIPPERY_73: i16 = 115;
pub const SURFACE_NOISE_VERY_SLIPPERY_74: i16 = 116;
pub const SURFACE_NOISE_VERY_SLIPPERY: i16 = 117;
pub const SURFACE_NO_CAM_COL_SLIPPERY: i16 = 121;
pub const SURFACE_NO_CAM_COL_VERY_SLIPPERY: i16 = 120;
pub const SURFACE_SWITCH: i16 = 122;
pub const TERRAIN_MASK: u16 = 7;
pub const TERRAIN_SLIDE: u16 = 6;
pub const SOUND_TERRAIN_DEFAULT: i8 = 0;
pub const SOUND_TERRAIN_GRASS: i8 = 1;
pub const SOUND_TERRAIN_WATER: i8 = 2;
pub const SOUND_TERRAIN_STONE: i8 = 3;
pub const SOUND_TERRAIN_SPOOKY: i8 = 4;
pub const SOUND_TERRAIN_SNOW: i8 = 5;
pub const SOUND_TERRAIN_ICE: i8 = 6;
pub const SOUND_TERRAIN_SAND: i8 = 7;
pub const LEVEL_LLL: i16 = 22;
pub const LEVEL_BOB: i16 = 9;

/// Every generated constant by name, for the oracle consistency test.
pub const ALL: [(&str, i64); 85] = [
    ("ACT_TWIRLING", ACT_TWIRLING as i64),
    ("ACT_SHOT_FROM_CANNON", ACT_SHOT_FROM_CANNON as i64),
    ("ACT_LONG_JUMP", ACT_LONG_JUMP as i64),
    ("ACT_SLIDE_KICK", ACT_SLIDE_KICK as i64),
    ("ACT_BBH_ENTER_SPIN", ACT_BBH_ENTER_SPIN as i64),
    ("ACT_LAVA_BOOST", ACT_LAVA_BOOST as i64),
    ("ACT_FALL_AFTER_STAR_GRAB", ACT_FALL_AFTER_STAR_GRAB as i64),
    ("ACT_GETTING_BLOWN", ACT_GETTING_BLOWN as i64),
    ("ACT_GROUND_POUND", ACT_GROUND_POUND as i64),
    ("ACT_FLYING", ACT_FLYING as i64),
    ("ACT_CRAWLING", ACT_CRAWLING as i64),
    ("ACT_QUICKSAND_DEATH", ACT_QUICKSAND_DEATH as i64),
    ("ACT_IDLE", ACT_IDLE as i64),
    ("ACT_WALKING", ACT_WALKING as i64),
    ("ACT_FREEFALL", ACT_FREEFALL as i64),
    ("ACT_JUMP", ACT_JUMP as i64),
    ("ACT_FLAG_STATIONARY", ACT_FLAG_STATIONARY as i64),
    ("ACT_FLAG_MOVING", ACT_FLAG_MOVING as i64),
    ("ACT_FLAG_AIR", ACT_FLAG_AIR as i64),
    ("ACT_FLAG_INTANGIBLE", ACT_FLAG_INTANGIBLE as i64),
    ("ACT_FLAG_INVULNERABLE", ACT_FLAG_INVULNERABLE as i64),
    ("ACT_FLAG_RIDING_SHELL", ACT_FLAG_RIDING_SHELL as i64),
    (
        "ACT_FLAG_CONTROL_JUMP_HEIGHT",
        ACT_FLAG_CONTROL_JUMP_HEIGHT as i64,
    ),
    ("ACT_FLAG_METAL_WATER", ACT_FLAG_METAL_WATER as i64),
    ("MARIO_VANISH_CAP", MARIO_VANISH_CAP as i64),
    ("MARIO_METAL_CAP", MARIO_METAL_CAP as i64),
    ("MARIO_WING_CAP", MARIO_WING_CAP as i64),
    ("MARIO_UNKNOWN_08", MARIO_UNKNOWN_08 as i64),
    ("MARIO_UNKNOWN_30", MARIO_UNKNOWN_30 as i64),
    ("INPUT_A_DOWN", INPUT_A_DOWN as i64),
    ("GROUND_STEP_LEFT_GROUND", GROUND_STEP_LEFT_GROUND as i64),
    ("GROUND_STEP_NONE", GROUND_STEP_NONE as i64),
    ("GROUND_STEP_HIT_WALL", GROUND_STEP_HIT_WALL as i64),
    (
        "GROUND_STEP_HIT_WALL_STOP_QSTEPS",
        GROUND_STEP_HIT_WALL_STOP_QSTEPS as i64,
    ),
    (
        "GROUND_STEP_HIT_WALL_CONTINUE_QSTEPS",
        GROUND_STEP_HIT_WALL_CONTINUE_QSTEPS as i64,
    ),
    (
        "AIR_STEP_CHECK_LEDGE_GRAB",
        AIR_STEP_CHECK_LEDGE_GRAB as i64,
    ),
    ("AIR_STEP_CHECK_HANG", AIR_STEP_CHECK_HANG as i64),
    ("AIR_STEP_NONE", AIR_STEP_NONE as i64),
    ("AIR_STEP_LANDED", AIR_STEP_LANDED as i64),
    ("AIR_STEP_HIT_WALL", AIR_STEP_HIT_WALL as i64),
    ("AIR_STEP_GRABBED_LEDGE", AIR_STEP_GRABBED_LEDGE as i64),
    ("AIR_STEP_GRABBED_CEILING", AIR_STEP_GRABBED_CEILING as i64),
    ("AIR_STEP_HIT_LAVA_WALL", AIR_STEP_HIT_LAVA_WALL as i64),
    ("SURFACE_DEFAULT", SURFACE_DEFAULT as i64),
    ("SURFACE_BURNING", SURFACE_BURNING as i64),
    ("SURFACE_HANGABLE", SURFACE_HANGABLE as i64),
    ("SURFACE_SLOW", SURFACE_SLOW as i64),
    ("SURFACE_VERY_SLIPPERY", SURFACE_VERY_SLIPPERY as i64),
    ("SURFACE_SLIPPERY", SURFACE_SLIPPERY as i64),
    ("SURFACE_NOT_SLIPPERY", SURFACE_NOT_SLIPPERY as i64),
    (
        "SURFACE_SHALLOW_QUICKSAND",
        SURFACE_SHALLOW_QUICKSAND as i64,
    ),
    ("SURFACE_DEEP_QUICKSAND", SURFACE_DEEP_QUICKSAND as i64),
    (
        "SURFACE_INSTANT_QUICKSAND",
        SURFACE_INSTANT_QUICKSAND as i64,
    ),
    (
        "SURFACE_DEEP_MOVING_QUICKSAND",
        SURFACE_DEEP_MOVING_QUICKSAND as i64,
    ),
    (
        "SURFACE_SHALLOW_MOVING_QUICKSAND",
        SURFACE_SHALLOW_MOVING_QUICKSAND as i64,
    ),
    ("SURFACE_QUICKSAND", SURFACE_QUICKSAND as i64),
    ("SURFACE_MOVING_QUICKSAND", SURFACE_MOVING_QUICKSAND as i64),
    (
        "SURFACE_INSTANT_MOVING_QUICKSAND",
        SURFACE_INSTANT_MOVING_QUICKSAND as i64,
    ),
    ("SURFACE_HORIZONTAL_WIND", SURFACE_HORIZONTAL_WIND as i64),
    ("SURFACE_VERTICAL_WIND", SURFACE_VERTICAL_WIND as i64),
    ("SURFACE_HARD", SURFACE_HARD as i64),
    ("SURFACE_HARD_SLIPPERY", SURFACE_HARD_SLIPPERY as i64),
    (
        "SURFACE_HARD_VERY_SLIPPERY",
        SURFACE_HARD_VERY_SLIPPERY as i64,
    ),
    (
        "SURFACE_HARD_NOT_SLIPPERY",
        SURFACE_HARD_NOT_SLIPPERY as i64,
    ),
    ("SURFACE_ICE", SURFACE_ICE as i64),
    ("SURFACE_NOISE_DEFAULT", SURFACE_NOISE_DEFAULT as i64),
    ("SURFACE_NOISE_SLIPPERY", SURFACE_NOISE_SLIPPERY as i64),
    (
        "SURFACE_NOISE_VERY_SLIPPERY_73",
        SURFACE_NOISE_VERY_SLIPPERY_73 as i64,
    ),
    (
        "SURFACE_NOISE_VERY_SLIPPERY_74",
        SURFACE_NOISE_VERY_SLIPPERY_74 as i64,
    ),
    (
        "SURFACE_NOISE_VERY_SLIPPERY",
        SURFACE_NOISE_VERY_SLIPPERY as i64,
    ),
    (
        "SURFACE_NO_CAM_COL_SLIPPERY",
        SURFACE_NO_CAM_COL_SLIPPERY as i64,
    ),
    (
        "SURFACE_NO_CAM_COL_VERY_SLIPPERY",
        SURFACE_NO_CAM_COL_VERY_SLIPPERY as i64,
    ),
    ("SURFACE_SWITCH", SURFACE_SWITCH as i64),
    ("TERRAIN_MASK", TERRAIN_MASK as i64),
    ("TERRAIN_SLIDE", TERRAIN_SLIDE as i64),
    ("SOUND_TERRAIN_DEFAULT", SOUND_TERRAIN_DEFAULT as i64),
    ("SOUND_TERRAIN_GRASS", SOUND_TERRAIN_GRASS as i64),
    ("SOUND_TERRAIN_WATER", SOUND_TERRAIN_WATER as i64),
    ("SOUND_TERRAIN_STONE", SOUND_TERRAIN_STONE as i64),
    ("SOUND_TERRAIN_SPOOKY", SOUND_TERRAIN_SPOOKY as i64),
    ("SOUND_TERRAIN_SNOW", SOUND_TERRAIN_SNOW as i64),
    ("SOUND_TERRAIN_ICE", SOUND_TERRAIN_ICE as i64),
    ("SOUND_TERRAIN_SAND", SOUND_TERRAIN_SAND as i64),
    ("LEVEL_LLL", LEVEL_LLL as i64),
    ("LEVEL_BOB", LEVEL_BOB as i64),
];
