#!/usr/bin/env python3
"""Authored field transport for camera comparisons, not reference behavior (MIT).

Generate the Rust exact-word record and C field adapter from one layout. The
native functions remain verbatim upstream excerpts. No ROM data is involved.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIELDS = []


def field(rust, native, kind):
    FIELDS.append((rust, native, kind))


def vector(rust, native, kind="f32"):
    for axis in range(3):
        field(f"{rust}[{axis}]", f"{native}[{axis}]", kind)


for rust, native, kind in [
    ("mode", "mode", "u8"), ("def_mode", "defMode", "u8"),
    ("yaw", "yaw", "i16"), ("next_yaw", "nextYaw", "i16"),
]:
    field("camera." + rust, "sComponentCamera." + native, kind)
vector("camera.focus", "sComponentCamera.focus")
vector("camera.pos", "sComponentCamera.pos")
field("camera.cutscene", "sComponentCamera.cutscene", "u8")
for rust, native in [("cur_focus", "curFocus"), ("cur_pos", "curPos"),
                     ("goal_focus", "goalFocus"), ("goal_pos", "goalPos")]:
    vector("lakitu." + rust, "gLakituState." + native)
for rust, native, kind in [
    ("mode", "mode", "u8"), ("def_mode", "defMode", "u8"),
    ("focus_distance", "focusDistance", "f32"),
    ("old_pitch", "oldPitch", "i16"), ("old_yaw", "oldYaw", "i16"),
]:
    field("lakitu." + rust, "gLakituState." + native, kind)
vector("lakitu.shake_magnitude", "gLakituState.shakeMagnitude", "i16")
for rust, native in [("shake_phase", "Phase"), ("shake_velocity", "Vel"), ("shake_decay", "Decay")]:
    for i, axis in enumerate(["Pitch", "Yaw", "Roll"]):
        field(f"lakitu.{rust}[{i}]", "gLakituState.shake" + axis + native, "i16")
for name in ["roll", "yaw"]:
    field("lakitu." + name, "gLakituState." + name, "i16")
field("lakitu.next_yaw", "gLakituState.nextYaw", "i16")
vector("lakitu.focus", "gLakituState.focus")
vector("lakitu.pos", "gLakituState.pos")
for rust, native in [("foc_h_speed", "focHSpeed"), ("foc_v_speed", "focVSpeed"),
                     ("pos_h_speed", "posHSpeed"), ("pos_v_speed", "posVSpeed")]:
    field("lakitu." + rust, "gLakituState." + native, "f32")
field("lakitu.key_dance_roll", "gLakituState.keyDanceRoll", "i16")
field("lakitu.last_frame_action", "gLakituState.lastFrameAction", "u32")
for rust, native, kind in [
    ("pos_pitch", "posPitch", "i16"), ("pos_yaw", "posYaw", "i16"), ("pos_dist", "posDist", "f32"),
    ("foc_pitch", "focPitch", "i16"), ("foc_yaw", "focYaw", "i16"), ("foc_dist", "focDist", "f32"),
    ("frames_left", "framesLeft", "i32"),
]:
    field("transition." + rust, "sModeTransition." + native, kind)
vector("transition.mario_pos", "sModeTransition.marioPos")
for rust, native, kind in [
    ("status", "sStatusFlags", "i16"), ("movement", "gCameraMovementFlags", "u16"),
    ("yaw_speed", "sYawSpeed", "i16"),
]:
    field(rust, native, kind)
for rust, native in [("old_pos", "sOldPosition"), ("old_focus", "sOldFocus"),
                     ("player2_focus_offset", "sPlayer2FocusOffset")]:
    vector(rust, native)
for i, axis in enumerate(["Pitch", "Yaw", "Roll"]):
    field(f"handheld_angles[{i}]", "sHandheldShake" + axis, "i16")
for rust, native, kind in [
    ("handheld_magnitude", "sHandheldShakeMag", "i16"),
    ("handheld_increment", "sHandheldShakeInc", "f32"),
    ("fov_shake.amplitude", "sFOVState.shakeAmplitude", "f32"),
    ("fov_shake.decay", "sFOVState.decay", "i16"),
    ("fov_shake.speed", "sFOVState.shakeSpeed", "i16"),
    ("new_mode", "sModeInfo.newMode", "i16"), ("last_mode", "sModeInfo.lastMode", "i16"),
    ("c_up_pitch", "sCUpCameraPitch", "i16"), ("mode_offset_yaw", "sModeOffsetYaw", "i16"),
    ("lakitu_dist", "sLakituDist", "i16"), ("lakitu_pitch", "sLakituPitch", "i16"),
    ("area_yaw_change", "sAreaYawChange", "i16"), ("pan_distance", "sPanDistance", "f32"),
    ("cannon_y_offset", "sCannonYOffset", "f32"),
]:
    field(rust, native, kind)

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
rust = ["// Authored field transport (MIT); generated by oracle/tools/lakitu_layout.py.\n",
        f"pub const STATE_WORDS: usize = {len(FIELDS)};\n",
        "pub const STATE_FIELD_NAMES: [&str; STATE_WORDS] = [\n"]
rust += [f'    "{r}",\n' for r, _, _ in FIELDS]
rust += ["];\nimpl super::Rig {\n    pub fn state_words(&self) -> [u32; STATE_WORDS] {\n        [\n"]
for r, _, kind in FIELDS:
    if kind == "f32":
        expr = f"self.{r}.to_bits()"
    elif kind == "i16":
        expr = f"self.{r} as i32 as u32"
    elif kind == "u32":
        expr = f"self.{r}"
    else:
        expr = f"self.{r} as u32"
    rust.append(f"            {expr},\n")
rust += ["        ]\n    }\n}\n"]
native = ["/* Authored field transport (MIT); generated by oracle/tools/lakitu_layout.py. */\n",
          f"#define LAKITU_STATE_WORDS {len(FIELDS)}\n",
          "static void load_lakitu_words(const u32 *words) {\n"]
for i, (_, n, kind) in enumerate(FIELDS):
    native.append(f"    memcpy(&{n}, &words[{i}], 4);\n" if kind == "f32" else f"    {n} = ({kind.replace('i', 's')})words[{i}];\n")
native.append("}\nstatic void store_lakitu_words(u32 *words) {\n")
for i, (_, n, kind) in enumerate(FIELDS):
    native.append(f"    words[{i}] = bits({n});\n" if kind == "f32" else f"    words[{i}] = (u32)({kind.replace('i', 's')})({n});\n")
native.append("}\n")
for path, text in [(ROOT / "src/simulation/camera/lakitu/record.rs", "".join(rust)),
                   (ROOT / "oracle/c/lakitu_state.inc.c", "".join(native))]:
    if args.check:
        if not path.exists() or path.read_text() != text:
            raise SystemExit(f"generated layout differs: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
